#!/bin/bash

# Check for existence of git.
which git >/dev/null
if [[ $? != 0 ]]; then
  printf "Failed to find 'git' (please install or update your path).\n"
  exit 1
fi

# Get top-level directory so we can look for tools/pre-commit file.
directory=$(git rev-parse --show-toplevel)

if [[ ! -f "${directory}/pre-commit" ]]; then
  printf "Failed to find 'pre-commit'."
  exit 1
fi

if [[ ! -f "${directory}/.clang-format" ]]; then
  printf "Failed to find '.clang-format'."
  exit 1
fi

ln -s -f ../../dev-tools/pre-commit "${directory}/../.git/hooks/pre-commit"
cp .clang-format "${directory}/.."
