#!/bin/bash

source dev-tools/check-code-style/check_style.sh

run_checks(){
   check_style_of_files_in_commit
}

case "$1" in
  --help )
    echo "Performs checks on files to be committed"
    ;;
  * )
    run_checks
    ;;
esac
