# The name of this file should be `action.yml` , `action.yaml` or `Dockerfile`.

name: 'Check Code Style'
desciption: 'Check files for correct code style'

runs:
  using: "composite"
  steps:
    - name: Check all .cc , .h, .proto files for correct code style
      run: | 
        chmod +x dev-tools/check-code-style/check_style_of_all_files.sh
        dev-tools/check-code-style/check_style_of_all_files.sh
      shell: bash

    - name: Install buildifier for .bzl files
      run: brew install buildifier
      shell: bash

    - name: Check all .bzl, .bazel files for correct code style
      run: |
        chmod +x dev-tools/check-code-style/check_style_bzl.sh
        dev-tools/check-code-style/check_style_bzl.sh    
      shell: bash
