# The name of this file should be `action.yml` , `action.yaml` or `Dockerfile`.

name: 'Check Code Style'
desciption: 'Check files for correct code style'

inputs:
  os: 
    description: 'Specify operating system on wich this action will run'
    required: 'false'
    default: 'ubuntu-latest'

runs-on: ${{ inputs.os }}
  using: "composite"
  steps:
    - name: Check all .cc , .h, .proto files for correct code style
      run: | 
        chmod +x ${{ github.action_path }}/check_style_of_all_files.sh
        ${{ github.action_path }}/check_style_of_all_files.sh
      shell: bash

    - name: Install buildifier for .bzl files
      run: brew install buildifier
      shell: bash

    - name: Check all .bzl, .bazel files for correct code style
      run: |
        chmod +x dev-tools/check-code-style/check_style_bzl.sh
        ${{ github.action_path }}/check_style_bzl.sh    
      shell: bash
