# The name of this file should be `action.yml` , `action.yaml` or `Dockerfile`.

name: 'Check Code Style'
desciption: 'Check files for correct code style'

runs:
  using: "composite"
  steps:
    - name: Run bootstrap
      run: cd dev-tools/ && ./bootstrap
      # The `shell` section is mandatory. Without it we will get
      # the following error:
      # ***  Required property is missing: shell.  
      shell: bash

    - name: Check all .cc , .h, .proto files for correct code style
      run: chmod +x dev-tools/check_style.sh && dev-tools/./check_style.sh
      shell: bash

    - name: Install buildifier for .bzl files
      run: brew install buildifier
      shell: bash

    - name: Check all .bzl, .bazel files for correct code style
      run: chmod +x dev-tools/check_style_bzl.sh && dev-tools/./check_style_bzl.sh    
      shell: bash
